apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins
spec:
  nfs:
    path: /opt/kubernetes/jenkins
    server: 10.100.10.1
  accessModes: ["ReadWriteOnce"]
  capacity:
    storage: 1Gi
#  mountOptions:
#    - nfsvers=4.1
